# public/openapi.yaml
openapi: 3.0.0
info:
  title: Juego REST API
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: Servidor de desarrollo local

paths:
  /games:
    get:
      summary: Obtener juego
      description: obtener juego
      tags:
        - Game Status
      responses:
        '200':
          description: Estado del juego recuperado exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      board:
                        type: array
                        description: Estado actual del tablero.
                        items:
                          type: string
                      next_player:
                        type: string
                        example: X
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal Server Error